sudo: required
services:
  - docker

before_install:
  - docker build -t filip505/docker-react -f dockerfile.dev .

script:
  - docker run filip505/docker-react npm test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-963568967312"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id:  $AWS_ACCESS_KEY
  seacret_access_key:
    secure: "$AWS_SECRET_KEY"

#     access_key_id: $AWS_ACCESS_KEY
# secret_access_key: $AWS_SECRET_KEY